import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "@/components/ui/toaster";
import { NavBar } from "@/components/NavBar";
import { auth } from "@/auth";

export const metadata: Metadata = {
  title: "Create Task",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        <ThemeProvider attribute="class" defaultTheme="system">
          <NavBar user={session?.user} />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
